<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Credentials: true");
header("Access-Control-Allow-Methods: POST, GET, DELETE, PUT");
header("Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers");

if (empty($_POST['token'])) {
    echo json_encode(["status" => "error", "errorcode" => "no_token", "message" => "Token is required"]);
    exit;
}

include 'Config.php';

$WH = $_POST['WH'];
$token = $_POST['token'];
$response = ["status" => "error", "message" => "Invalid request"];

$check = $DbCon->query("SELECT USER_ID FROM MAS_USERS WHERE USER_TOKEN = '$token'");

if ($check->num_rows > 0) {
    $current_date = date('d-m-Y H:i:s'); // Format: 28-02-2025 03:15:19
    if ($WH == 'all') {
        $queries = [

            "MAINWAREHOUSE" => "SELECT (SUM(M.S_QTY *M.S_SALERATE)) AS result FROM TRN_MAINSTOCK M;",
            "MAINWAREHOUSEQTY" => "SELECT SUM(M.S_QTY) AS result FROM TRN_MAINSTOCK M;",

            "TODAY_SALES" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE();",
            "TODAY_SALESQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE();",

            "YESTERDAY_SALES" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE() - INTERVAL 1 DAY;",
            "YESTERDAY_SALESQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE() - INTERVAL 1 DAY;",

            "LAST_IIIDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 3 DAY) AND CURDATE();",
            "LAST_IIIDAYSQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 3 DAY) AND CURDATE();",

            "LAST_XVDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 15 DAY) AND CURDATE();",
            "LAST_XVDAYSQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 15 DAY) AND CURDATE();",

            "LAST_XXXXVDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 45 DAY) AND CURDATE();",
            "LAST_XXXXVDAYSQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 45 DAY) AND CURDATE();",

            "LAST_WEEK" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY);",
            "LAST_WEEKQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY);",

            "LAST_MONTH" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY);",
            "LAST_MONTHQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY);",

            "TOT_TRASFER" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS='A' AND WH_TOID!='all'",
            "TOT_TRASFERQTY" => "SELECT SUM(NO_ITEMS) AS result FROM STK_TRANSACTION WHERE TRN_STATUS='A' AND WH_TOID!='all'",

            // --------------------------SUBWARE HOUSE DETAILS
            "SUBWAREHOUSE" => "SELECT (SUM(W.S_QTY *W.S_SALERATE)) AS result FROM TRN_WHSTOCK W",
            "SUBWAREHOUSEQTY" => "SELECT SUM(W.S_QTY) AS result FROM TRN_WHSTOCK W",

            "WH_TRASFER" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS='A' AND WH_TOID='all'",
            "WH_TRASFERQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all'), 0) - COALESCE((SELECT COUNT(RETURN_ID)FROM TRN_RETURNS), 0) AS result;",

            "WH_MONTH" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY);",
            "WH_MONTHQTY" => "SELECT COALESCE(( SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY) ), 0)-COALESCE(( SELECT COUNT(RETURN_ID)FROM TRN_RETURNS WHERE DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY) ), 0) AS result;",

            "WH_WEEK" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY);",
            "WH_WEEKQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)), 0) - COALESCE(( SELECT COUNT(RETURN_ID)FROM TRN_RETURNS WHERE DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)), 0) AS result;",

            "WHTODAY_SALES" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE();",
            "WHTODAY_SALESQTY" => "SELECT(COALESCE((SELECT SUM(NO_ITEMS)FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE()), 0)-COALESCE((SELECT COUNT(RETURN_ID)FROM TRN_RETURNS R WHERE DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) = CURDATE()), 0))  AS result",

            "WHYESTERDAY_SALES" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE() - INTERVAL 1 DAY;",
            "WHYESTERDAY_SALESQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION  WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE() - INTERVAL 1 DAY), 0) - (SELECT COUNT(RETURN_ID)FROM TRN_RETURNS R WHERE DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) = CURDATE() - INTERVAL 1 DAY) AS result;",

            "WHLAST_IIIDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 3 DAY) AND CURDATE();",
            "WHLAST_IIIDAYSQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 2 DAY AND CURDATE()), 0)- (SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 3 DAY AND CURDATE() - INTERVAL 1 DAY) AS result;",

            "WHLAST_XVDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 15 DAY) AND CURDATE();",
            "WHLAST_XVDAYSQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 14 DAY AND CURDATE()), 0)-(SELECT COUNT(RETURN_ID)FROM TRN_RETURNS R WHERE DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 14 DAY AND CURDATE()) AS result;",

            "WHLAST_XXXXVDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 45 DAY) AND CURDATE();",
            "WHLAST_XXXXVDAYSQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 44 DAY AND CURDATE()), 0)-(SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y'))  BETWEEN CURDATE() - INTERVAL 44 DAY AND CURDATE()) AS result;",
        ];
    } else {
        $queries = [
            "SUBWAREHOUSE" => "SELECT (SUM(W.S_QTY *W.S_SALERATE)) AS result FROM TRN_WHSTOCK W WHERE W.WH_ID ='$WH';",
            "SUBWAREHOUSEQTY" => "SELECT SUM(W.S_QTY) AS result FROM TRN_WHSTOCK W WHERE W.WH_ID ='$WH'; ",

            "WH_TRASFER" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS='A' AND WH_TOID='all'  AND WH_FROMID='$WH';",
            "WH_TRASFERQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND  WH_TOID = 'all' AND WH_FROMID='$WH'), 0) - COALESCE((SELECT COUNT(RETURN_ID)FROM TRN_RETURNS WHERE  WH_ID='$WH'), 0) AS result;",

            "WH_MONTH" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all' AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY);",
            "WH_MONTHQTY" => "SELECT COALESCE(( SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID='$WH' AND WH_TOID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY) ), 0)-COALESCE(( SELECT COUNT(RETURN_ID)FROM TRN_RETURNS WHERE  WH_ID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL DAY(CURDATE()) - 1 DAY) ), 0) AS result;",

            "WH_WEEK" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_TOID = 'all' AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY);",
            "WH_WEEKQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID='$WH' AND WH_TOID = 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)), 0) - COALESCE(( SELECT COUNT(RETURN_ID)FROM TRN_RETURNS WHERE  WH_ID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)), 0) AS result;",

            "WHTODAY_SALES" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all' AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE();",
            "WHTODAY_SALESQTY" => "SELECT COALESCE(( SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = '$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE() ), 0) - COALESCE(( SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE R.WH_ID = '$WH' AND DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) = CURDATE() ), 0) AS result;",

            "WHYESTERDAY_SALES" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all'  AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE() - INTERVAL 1 DAY;",
            "WHYESTERDAY_SALESQTY" => "SELECT COALESCE(( SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = '$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) = CURDATE()- INTERVAL 1 DAY ), 0) - COALESCE(( SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE R.WH_ID = '$WH' AND DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) = CURDATE()- INTERVAL 1 DAY ), 0) AS result;",

            "WHLAST_IIIDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all'  AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 3 DAY) AND CURDATE();",
            "WHLAST_IIIDAYSQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A'  AND WH_FROMID = '$WH' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 2 DAY AND CURDATE()), 0) - (SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE WH_ID = '$WH' AND DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 3 DAY AND CURDATE() - INTERVAL 1 DAY) AS result;",

            "WHLAST_XVDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all'  AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 15 DAY) AND CURDATE();",
            "WHLAST_XVDAYSQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = '$WH' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 14 DAY AND CURDATE()), 0)-(SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE WH_ID = '$WH' AND DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 14 DAY AND CURDATE() - INTERVAL 1 DAY) AS result;",

            "WHLAST_XXXXVDAYS" => "SELECT SUM(TOTAL_AMT) AS result FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID != 'all'  AND WH_FROMID='$WH' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN DATE_SUB(CURDATE(), INTERVAL 45 DAY) AND CURDATE();",
            "WHLAST_XXXXVDAYSQTY" => "SELECT COALESCE((SELECT SUM(NO_ITEMS) FROM STK_TRANSACTION WHERE TRN_STATUS = 'A' AND WH_FROMID = '$WH' AND WH_FROMID != 'all' AND DATE(STR_TO_DATE(CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 44 DAY AND CURDATE()), 0) -(SELECT COUNT(RETURN_ID) FROM TRN_RETURNS R WHERE WH_ID = '$WH'  AND DATE(STR_TO_DATE(R.CREATED_DATE, '%d-%m-%Y')) BETWEEN CURDATE() - INTERVAL 44 DAY AND CURDATE() - INTERVAL 1 DAY) AS result;",

        ];
    }


    // foreach ($queries as $key => $query) {
    //     $result = $DbCon->query($query);
    //     $data = $result->fetch_assoc();
    //     $response[$key] = $data['result'] ?? 0;
    // }

    foreach ($queries as $key => $query) {
        $result = $DbCon->query($query);
        $data = $result->fetch_assoc();
        
        $value = isset($data['result']) ? round($data['result'], 2) : 0;
        $response[$key] = number_format($value, 2, '.', '');
    }
    

    $response["status"] = "ok";
    $response["current_date"] = $current_date;
}

echo json_encode($response);
mysqli_close($DbCon);
